ANIMES_LIST = [
    ".hack//Legend Of The Twilight",
    ".hack//Sign",
    ".hack//roots",
    "009-1",
    "07-Ghost",
    "100 Sleeping Princes and the Kingdom of Dreams",
    "100% Teacher Pascal",
    "11eyes",
    "12-sai.: Chicchana Mune no Tokimeki",
    "12-sai.: Chicchana Mune no Tokimeki 2nd Season",
    "18if",
    "22/7",
    "25-sai no Joshikousei",
    "3D Kanojo: Real Girl 2nd Season",
    "91 Days",
    "A Bridge to the Starry Skies",
    "A Centaur's Life",
    "A Certain Magical Index",
    "A Certain Magical Index II",
    "A Certain Magical Index III",
    "A Certain Scientific Accelerator",
    "A Certain Scientific Railgun",
    "A Certain Scientific Railgun S",
    "A Certain Scientific Railgun T",
    "A Dark Rabbit has Seven Lives",
    "A Dog of Flanders",
    "A Good Librarian Like a Good Shepherd",
    "A Little Princess Sara",
    "A Little Snow Fairy Sugar",
    "A Lull in the Sea",
    "A Place Further Than The Universe",
    "A Sister's All You Need",
    "A Thirty-Year Old's Health and Physical Education",
    "A Town Where You Live",
    "A-Channel",
    "A.D. Police:To Protect and Serve",
    "A3! Season Spring & Summer",
    "ACCA:13-Territory Inspection Dept.",
    "AFTERLOST",
    "AHO-GIRL",
    "AKB0048",
    "AKB0048:Next Stage",
    "APPARE-RANMAN!",
    "Absolute Duo",
    "Accel World",
    "Ace Attorney",
    "Ace Attorney Season 2",
    "Ace of Diamond",
    "Ace of Diamond Act II",
    "Ace of Diamond:Second Season",
    "Ace wo Nerae!",
    "Action Heroine Cheer Fruits",
    "Active Raid",
    "Active Raid Second",
    "Actors: Songs Connection",
    "Actually, I am...",
    "Adachi and Shimamura",
    "Aesthetica of a Rogue Hero",
    "Africa Salaryman",
    "Afro Samurai",
    "After School Dice Club",
    "After War Gundam X",
    "After the Rain",
    "Aggretsuko",
    "Aguu:Genius Dolls",
    "Ah My Buddha",
    "Ah My Buddha Katsu",
    "Ah! My Goddess",
    "Ah! My Goddess:Flights of Fancy",
    "Ahiru no Sora",
    "Ai Shoujo Pollyanna Story",
    "Ai Tenchi Muyou!",
    "Ai Yori Aoshi",
    "Ai Yori Aoshi:Enishi",
    "Ai-Mai-Mi",
    "Ai-Mai-Mi Mousou Catastrophe",
    "Ai-Mai-Mi Surgical Friends",
    "Aikatsu Friends!",
    "Aikatsu Stars!",
    "Aikatsu!",
    "Air",
    "Air Gear",
    "Air Master",
    "Aishiteruze Baby\u2605\u2605",
    "Aiura",
    "Ajin 2nd Season",
    "Ajin:Demi-Human",
    "Akahori's Heretical Hour Love Game",
    "Akame ga Kill!",
    "Akane Iro ni Somaru Saka",
    "Akashic Records of Bastard Magic Instructor",
    "Akiba's Trip The Animation",
    "Akiba-chan",
    "Akihabara Dennou-gumi",
    "Akikan!",
    "Akudama Drive",
    "Alderamin on the Sky",
    "Aldnoah.Zero",
    "Alice & Zoroku",
    "Alice or Alice",
    "All Out!!",
    "All Purpose Cultural Cat Girl Nuku Nuku TV",
    "Allison & Lillia",
    "Alps no Shoujo Heidi",
    "Altair:A Record of Battles",
    "Amagami SS",
    "Amagami SS+ plus",
    "Amagi Brilliant Park",
    "Amai Choubatsu: Watashi wa Kanshu Senyou Pet",
    "Amanchu!",
    "Amanchu! Advance",
    "Amatsuki",
    "Amazing Stranger",
    "Ame-Con!!",
    "Ame-iro Cocoa: Side G",
    "Amnesia",
    "And Yet The Town Moves",
    "And you thought there is never a girl online?",
    "Android Kikaider",
    "Ange Vierge",
    "Angel Beats!",
    "Angel Heart",
    "Angel Links",
    "Angel Tales",
    "Angel's 3Piece!",
    "Angels of Death",
    "Angolmois:Record of Mongol Invasion",
    "Ani ni Tsukeru Kusuri wa Nai!",
    "Ani ni Tsukeru Kusuri wa Nai! 2",
    "Ani ni Tsukeru Kusuri wa Nai! 3",
    "Anima Yell!",
    "Anime de Training! Ex",
    "Anime de Training! Xx",
    "Anime-Gataris",
    "Anne of Green Gables",
    "Anne-Happy",
    "Anonymous Noise",
    "Another",
    "AntiMagic Academy 35th Test Platoon",
    "Antique Bakery",
    "Ao-chan Can't Study!",
    "Aoharu x Machinegun",
    "Aoi Bungaku Series",
    "Aokana:Four Rhythm Across the Blue",
    "Aooni The Blue Monster",
    "Aquarian Age:Sign for Evolution",
    "Aquarion",
    "Aquarion Evol",
    "Aquarion Logos",
    "Arad Senki: Slap Up Party",
    "Araiya-san!: Ore to Aitsu ga Onnayu de!?",
    "Arakawa Under the Bridge",
    "Arakawa Under the Bridge x Bridge",
    "Arata:The Legend",
    "Arc the Lad",
    "Are You Lost?",
    "Area 88 (TV)",
    "Argento Soma",
    "Argevollen",
    "Aria the Animation",
    "Aria the Natural",
    "Aria the Origination",
    "Aria the Scarlet Ammo",
    "Aria the Scarlet Ammo AA",
    "Arifureta:From Commonplace to World's Strongest",
    "Arjuna",
    "Armed Girl's Machiavellism",
    "Armed Librarians:The Book of Bantorra",
    "Armored Trooper Votoms",
    "Arpeggio of Blue Steel -Ars Nova-",
    "Arte",
    "As Miss Beelzebub Likes.",
    "Ascendance of a Bookworm",
    "Ascendance of a Bookworm Part 2",
    "Asobi Asobase:Workshop of Fun",
    "Assassination Classroom",
    "Assassination Classroom Second Season",
    "Assassins Pride",
    "Assault Lily: Bouquet",
    "Astarotte's Toy",
    "Asteroid in Love",
    "Astra Lost in Space",
    "Astro Boy",
    "Astro Boy (1980)",
    "Astro Boy (2003)",
    "Asura Cryin'",
    "Asura Cryin' 2",
    "At The Mercy of The Sky",
    "Atom: The Beginning",
    "Attack on Titan",
    "Attack on Titan Season 2",
    "Attack on Titan Season 3",
    "Attack on Titan Season 3 Part 2",
    "Attack on Titan:Junior High",
    "Aura Battler Dunbine",
    "Avenger",
    "Ayakashi",
    "Ayakashi: Japanese Classic Horror",
    "Azumanga Daioh:The Animation",
    "Azur Lane",
    "B'T X",
    "B-Project: Kodou*Ambitious",
    "B-Project: Zecchou*Emotion",
    "BBK/BRNK",
    "BBK/BRNK:The Gentle Giants of the Galaxy",
    "BLEND-S",
    "BLOOD-C",
    "BOFURI:I Don't Want to Get Hurt, so I'll Max Out My Defense.",
    "BTOOOM!",
    "Baby Steps",
    "Baby Steps 2nd Season",
    "Baby and Me",
    "Babylon",
    "Baccano!",
    "Back Street Girls:Gokudolls",
    "Baka & Test - Summon the Beasts",
    "Baka & Test \u2013 Summon the Beasts 2",
    "Bakemonogatari",
    "Bakugan Battle Brawlers",
    "Bakugan:Gundalian Invaders",
    "Bakugan:Mechtanium Surge",
    "Bakugan:New Vestroia",
    "Bakuman.",
    "Bakumatsu",
    "Bakumatsu Gijinden Roman",
    "Bakumatsu: Crisis",
    "Bakuon!!",
    "Bamboo Blade",
    "BanG Dream!",
    "BanG Dream! 2nd Season",
    "BanG Dream! 3rd Season",
    "BanG Dream! Garupa\u2606Pico",
    "Banana Fish",
    "Bananya",
    "Bananya and the Curious Bunch",
    "Banner of the Stars",
    "Banner of the Stars II",
    "Barakamon",
    "Bartender",
    "Basilisk",
    "Basilisk:The Ouka Ninja Scrolls",
    "Basquash!",
    "Battery",
    "Battle Athletes Victory",
    "Battle Doll Angelic Layer",
    "Battle Girl High School",
    "Battle Girls:Time Paradox",
    "Battle Programmer Shirase",
    "Beastars",
    "Beatless",
    "Beatless Final Stage",
    "Beautiful Bones -Sakurako's Investigation-",
    "Beck:Mongolian Chop Squad",
    "Beelzebub",
    "Beet the Vandel Buster",
    "Beet the Vandel Buster Excellion",
    "Before Green Gables",
    "Bem",
    "Ben-To",
    "Bermuda Triangle: Colorful Pastrale",
    "Berserk",
    "Berserk:Season II",
    "Best Student Council",
    "Betterman",
    "Between the Sky and Sea",
    "Beyblade",
    "Beyblade G Revolution",
    "Beyblade V-Force",
    "Beyblade:Metal Fury",
    "Beyblade:Metal Masters",
    "Beyblade:Shogun Steel",
    "Beyond the Boundary",
    "Beyond the Heavens",
    "Big Order (TV)",
    "Big Windup!",
    "Big Windup! 2",
    "Bihada Ichizoku",
    "Bikini Warriors",
    "Binan Koukou Chikyuu Boueibu Happy Kiss!",
    "Binbou Shimai Monogatari",
    "Binchou-tan",
    "Bird of Fire",
    "Birdy the Mighty:Decode",
    "Birdy the Mighty:Decode 02",
    "Black Blood Brothers",
    "Black Bullet",
    "Black Butler",
    "Black Butler II",
    "Black Butler:Book of Circus",
    "Black Cat",
    "Black Jack (TV)",
    "Black Jack 21",
    "Black Lagoon",
    "Black Lagoon:The Second Barrage",
    "Black Rock Shooter",
    "Blade",
    "Blade & Soul",
    "Blade Dance of the Elementalers",
    "Blade of the Immortal",
    "Blassreiter",
    "Blast of Tempest",
    "BlazBlue:Alter Memory",
    "Bleach",
    "Blessing of the Campanella",
    "Blood Blockade Battlefront",
    "Blood Blockade Battlefront & Beyond",
    "Blood Lad",
    "Blood+",
    "Bloodivores",
    "Bloom Into You",
    "Blue Dragon",
    "Blue Dragon:The Seven Dragons of the Heavens",
    "Blue Drop",
    "Blue Exorcist",
    "Blue Exorcist:Kyoto Saga",
    "Blue Gender",
    "Blue Legend Shoot!",
    "Blue Seed",
    "Blue Spring Ride",
    "Boarding School Juliet",
    "Bobobo-bo Bo-bobo",
    "Bodacious Space Pirates",
    "Boku no Imouto wa \"Osaka Okan\"",
    "Boku no Tonari ni Ankoku Hakaishin ga Imasu.",
    "Bokura ga Ita",
    "Bokurano",
    "Boogiepop Phantom",
    "Boogiepop and Others",
    "Bottle Fairy",
    "Boys Be...",
    "Brain Powerd",
    "Brave 10",
    "Brave Beats",
    "Brave Witches",
    "Breakers",
    "Brigadoon",
    "Brighter Than the Dawning Blue",
    "Broken Blade",
    "Brother, Dear Brother",
    "Brothers Conflict",
    "Brynhildr in the Darkness",
    "Bubblegum Crisis Tokyo 2040",
    "Buddy Complex",
    "Bungo Stray Dogs",
    "Bungo Stray Dogs 2",
    "Bungo and Alchemist -Gears of Judgement-",
    "Bungou Stray Dogs 3rd Season",
    "Bunny Drop",
    "Burn Up Excess",
    "Burn Up Scramble",
    "Burst Angel",
    "Bus Gamer",
    "Buso Renkin",
    "Busou Shinki:Armored War Goddess",
    "Butlers: Chitose Momotose Monogatari",
    "Buzzer Beater",
    "Buzzer Beater 2nd Season",
    "By the Grace of the Gods",
    "CHOYOYU!:High School Prodigies Have It Easy Even in Another World!",
    "CLAMP School Detectives",
    "Caligula",
    "Campione!",
    "Canaan",
    "Candy Candy",
    "Canvas 2:Rainbow Colored Sketch",
    "Capeta",
    "Captain Earth",
    "Captain Tsubasa",
    "Captain Tsubasa (2018)",
    "Captain Tsubasa J",
    "Cardcaptor Sakura",
    "Cardcaptor Sakura:Clear Card",
    "Cardfight!! Vanguard",
    "Cardfight!! Vanguard Asia Circuit",
    "Cardfight!! Vanguard G",
    "Cardfight!! Vanguard G GIRS Crisis",
    "Cardfight!! Vanguard G Stride Gate",
    "Cardfight!! Vanguard Legion Mate",
    "Cardfight!! Vanguard Link Joker",
    "Carole & Tuesday",
    "Carried by the Wind:Tsukikage Ran",
    "Case File n\u00ba221:Kabukicho",
    "Casshern Sins",
    "Castle Town Dandelion",
    "Cat Planet Cuties",
    "Cat's Eye",
    "Cautious Hero:The Hero Is Overpowered but Overly Cautious",
    "Celestial Method",
    "Cells at Work!",
    "Cells at Work!!",
    "Cerberus",
    "Ceres, Celestial Legend",
    "Chaika -The Coffin Princess-",
    "Chaika -The Coffin Princess- Avenging Battle",
    "Chain Chronicle:The Light of Haecceitas",
    "Chance Triangle Session",
    "Chaos Dragon",
    "Charge!! Men's Private School",
    "Charlotte",
    "Cheating Craft",
    "Cheeky Angel",
    "Cheer Boys!!",
    "Chi's New Address",
    "Chi's Sweet Adventure",
    "Chi's Sweet Home",
    "Chibi\u2606Devi!",
    "Chidori RSC",
    "Chihayafuru",
    "Chihayafuru 2",
    "Chihayafuru 3",
    "Chikyuu Bouei Kigyou Dai-Guard",
    "Children of the Whales",
    "Chio's School Road",
    "Chiruran 1/2",
    "Chitose Get You!!",
    "Chivalry of a Failed Knight",
    "Chobits",
    "Chocotto Sister",
    "Choujigen Kakumei Anime: Dimension High School",
    "Chrome Shelled Regios",
    "Chronicles of the Going Home Club",
    "Chrono Crusade",
    "Chronos Ruler",
    "Chu-Bra",
    "Chuuka Ichiban!",
    "Ch\u00e4oS;Child",
    "Ch\u00e4oS;HEAd",
    "Cinderella Boy",
    "Cinderella Girls Gekijou 2nd Season",
    "Cinderella Girls Gekijou 3rd Season",
    "Cinderella Girls Gekijou: Climax Season",
    "Cinderella Nine",
    "Circlet Princess",
    "Citrus",
    "City Hunter",
    "City Hunter '91",
    "City Hunter 2",
    "City Hunter 3",
    "Clannad",
    "Clannad ~After Story~",
    "ClassicaLoid",
    "ClassicaLoid 2",
    "Classroom of the Elite",
    "Classroom\u2606Crisis",
    "Claymore",
    "Clean Freak! Aoyama-kun",
    "Clione no Akari",
    "Clockwork Planet",
    "Cluster Edge",
    "Cobra The Animation",
    "Code Geass:Lelouch of the Rebellion",
    "Code Geass:Lelouch of the Rebellion R2",
    "Code-E",
    "Code:Breaker",
    "Code:Realize ~Guardian of Rebirth~",
    "Colorful",
    "Comet Lucifer",
    "Comic Girls",
    "Comic Party",
    "Comic Party Revolution",
    "Conception",
    "Concrete Revolutio",
    "Concrete Revolutio: Choujin Gensou - The Last Song",
    "Convenience Store Boy Friends",
    "Cop Craft",
    "Coppelion",
    "Corpse Princess:Aka",
    "Corpse Princess:Kuro",
    "Cosmo Warrior Zero",
    "Cowboy Bebop",
    "Coyote Ragtime Show",
    "Crane Game Girls",
    "Crane Game Girls Galaxy",
    "Crest of the Stars",
    "Crois\u00e9e in a Foreign Labyrinth The Animation",
    "Cromartie High School",
    "Cross Ange:Rondo of Angel and Dragon",
    "Cross Game",
    "Crossing Time",
    "Cute High Earth Defense Club LOVE!",
    "Cute High Earth Defense Club LOVE! LOVE!",
    "Cutey Honey",
    "Cutey Honey F",
    "Cuticle Detective Inaba",
    "Cutie Honey Universe",
    "Cyborg 009",
    "C\u00b3 - CubexCursedxCurious",
    "D-Frag!",
    "D.C.II S.S.: Da Capo II Second Season",
    "D.C.II: Da Capo II",
    "D.C.III: Da Capo III",
    "D.C.S.S. ~Da Capo Second Season~",
    "D.C.~Da Capo~",
    "D.Gray-man",
    "D.Gray-man HALLOW",
    "D.N.Angel",
    "D4DJ First Mix",
    "DAKAICHI -I'm being harassed by the sexiest man of the year-",
    "DARLING in the FRANXX",
    "DD Fist of the North Star",
    "DD Fist of the North Star 2:Strawberry Flavor Plus",
    "DIVE!!",
    "DNA\u00b2",
    "DRAMAtical Murder",
    "Daa! Daa! Daa!",
    "Dagashi Kashi",
    "Dagashi Kashi 2",
    "Dai-Shogun:Great Revolution",
    "Daily Lives of High School Boys",
    "Daimidaler:Prince vs. Penguin Empire",
    "Damekko Doubutsu",
    "Damepri Anime Caravan",
    "Dance in the Vampire Bund",
    "Dance with Devils",
    "Dances with the Dragons",
    "Danchigai",
    "Danganronpa 3:The End of Hope's Peak High School - Despair Arc",
    "Danganronpa 3:The End of Hope's Peak High School - Future Arc",
    "Danganronpa:The Animation",
    "Daphne in the Brilliant Blue",
    "Darker than Black",
    "Darker than Black:Gemini of the Meteor",
    "Darwin's Game",
    "Date A Live",
    "Date A Live II",
    "Date A Live III",
    "Day Break Illusion",
    "Days",
    "Deadman Wonderland",
    "DearS",
    "Death March to the Parallel World Rhapsody",
    "Death Note",
    "Death Parade",
    "Deca-Dence",
    "Deltora Quest",
    "Demon King Daimao",
    "Demon Lord Dante",
    "Demon Lord, Retry!",
    "Demon Slayer:Kimetsu no Yaiba",
    "Den-noh Coil",
    "Denki-gai",
    "Descendants of Darkness",
    "Descending Stories:Showa Genroku Rakugo Shinju",
    "Desert Punk",
    "Destiny of the Shrine Maiden",
    "Detective Opera Milky Holmes 2",
    "Detective School Q",
    "Devil May Cry",
    "Devil Survivor 2 The Animation",
    "Devilman",
    "Devils and Realist",
    "Devils' Line",
    "Di Gi Charat",
    "Diabolik Lovers",
    "Diabolik Lovers II:More,Blood",
    "Diamond Daydreams",
    "Diary of Our Days at the Breakwater",
    "Didn't I Say to Make My Abilities Average in the Next Life?!",
    "Dies irae",
    "Digimon Adventure 02",
    "Digimon Data Squad",
    "Digimon Frontier",
    "Digimon Fusion",
    "Digimon Tamers",
    "Digimon Universe App Monsters",
    "Digimon:Digital Monsters",
    "Dimension W",
    "Dirty Pair",
    "Disgaea",
    "Divergence Eve",
    "Divine Gate",
    "Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?",
    "Doamayger-D",
    "Dog & Scissors",
    "Dog Days",
    "Dog Days'",
    "Dog Days''",
    "Dogeza de tanondemita",
    "Dojin Work",
    "Dokkoida?!",
    "Domestic Girlfriend",
    "Doraemon",
    "Dorei-ku The Animation",
    "Dorohedoro",
    "Dororo",
    "Double Decker! Doug & Kirill",
    "Double Wish",
    "Double-J",
    "Dr. Slump",
    "Dr. Slump: Arale-chan",
    "Dr. Stone",
    "Dragon Ball",
    "Dragon Ball GT",
    "Dragon Ball Super",
    "Dragon Ball Z",
    "Dragon Ball Z Kai",
    "Dragon Ball Z Kai:The Final Chapters",
    "Dragon Crisis!",
    "Dragon Drive",
    "Dragon Pilot:Hisone and Masotan",
    "Dragon Quest: Dai no Daibouken (TV)",
    "Dragonar Academy",
    "Dragonaut - The Resonance",
    "Dream Eater Merry",
    "Drifters",
    "Dropkick On My Devil!",
    "Dropout Idol Fruit Tart",
    "Dual! Parallel Trouble Adventure",
    "Duel Masters",
    "Durarara!!",
    "Durarara!! x2 Ketsu",
    "Durarara!! x2 Shou",
    "Durarara!! x2 Ten",
    "Dusk Maiden of Amnesia",
    "Dynamic Chord",
    "E's Otherwise",
    "ENDRO!",
    "ERASED",
    "Earl and Fairy",
    "Eat-Man",
    "Eat-Man '98",
    "Eden of The East",
    "Eden's Bowy",
    "El Cazador de la Bruja",
    "El Hazard: The Alternative World",
    "El-Hazard:The Wanderers",
    "Elegant Yokai Apartment Life",
    "Element Hunters",
    "Elemental Gelade",
    "Elfen Lied",
    "Emma:A Victorian Romance",
    "Emma:A Victorian Romance Season Two",
    "Encouragement of Climb",
    "Encouragement of Climb Season 2",
    "Encouragement of Climb Season 3",
    "Endless Orbit SSX",
    "Endride",
    "Engaged to the Unidentified",
    "Ensemble Stars!",
    "Ergo Proxy",
    "Erin",
    "Eromanga Sensei",
    "Escha & Logy no Atelier: Tasogare no Sora no Renkinjutsushi",
    "Eternal Alice",
    "Etotama",
    "Eureka Seven",
    "Eureka Seven AO",
    "Evil or Live",
    "Excel Saga",
    "Extra Olympia Kyklos",
    "Eyeshield 21",
    "Fafner of the Blue Sky",
    "Fairy Gone",
    "Fairy Tail",
    "Fairy Tail Final Series",
    "Fairy Tail Series 2",
    "Fairy gone Season 1 Part 2",
    "Fantasista Doll",
    "Fantastic Children",
    "Fantastic Detective Labyrinth",
    "Fastest Finger First",
    "Fate/Apocrypha",
    "Fate/Extra: Last Encore - Illustrias Tendousetsu",
    "Fate/Extra:Last Encore",
    "Fate/Grand Order:Absolute Demonic Front - Babylonia",
    "Fate/Kaleid Liner Prisma Illya",
    "Fate/Kaleid Liner Prisma Illya 2Wei Herz!",
    "Fate/Kaleid Liner Prisma Illya 2Wei!",
    "Fate/Zero",
    "Fate/Zero Season 2",
    "Fate/kaleid liner Prisma\u2606Illya 3rei!!",
    "Fate/stay night",
    "Fate/stay night [Unlimited Blade Works]",
    "Fate/stay night [Unlimited Blade Works] Season 2",
    "Fighting Spirit",
    "Fighting Spirit:New Challenger",
    "Figure 17: Tsubasa & Hikaru",
    "Final Approach",
    "Final Fantasy: Unlimited",
    "Fire Force",
    "Fire Force Season 2",
    "Fireball",
    "Fireball Charming",
    "Fireball Humorous",
    "First Love Monster",
    "Fist of the Blue Sky",
    "Fist of the North Star",
    "Fist of the North Star 2",
    "Flame of Recca",
    "Flip Flappers",
    "Flowers of Evil",
    "Flying Witch",
    "Food Wars! Shokugeki no Soma",
    "Food Wars! The Fifth Plate",
    "Food Wars! The Fourth Plate",
    "Food Wars! The Second Plate",
    "Food Wars! The Third Plate",
    "Food Wars! The Third Plate:Totsuki Train Arc",
    "Forest Fairy Five",
    "Forest of Piano",
    "Fortune Arterial: Akai Yakusoku",
    "Fractale",
    "Frame Arms Girl",
    "Free! - Eternal Summer",
    "Free! - Iwatobi Swim Club",
    "Free!: Dive to the Future",
    "Freezing",
    "Freezing Vibration",
    "Fresh Precure!",
    "From the New World",
    "Fruits Basket",
    "Fruits Basket 1st Season",
    "Fruits Basket 2nd Season",
    "Full Metal Panic!",
    "Full Metal Panic! Invisible Victory",
    "Full Metal Panic! The Second Raid",
    "Full Metal Panic? Fumoffu",
    "Fullmetal Alchemist",
    "Fullmetal Alchemist:Brotherhood",
    "Fushigi na Somera-chan",
    "Futakoi Alternative",
    "Futari wa Milky Holmes",
    "Future Boy Conan",
    "Fuuka",
    "Fuyu no Sonata",
    "G-On Riders",
    "GA: Geijutsuka Art Design Class",
    "GARO -VANISHING LINE-",
    "GARO:THE ANIMATION",
    "GATE",
    "GJ Club",
    "GRANBLUE FANTASY The Animation Season2",
    "GS Mikami",
    "GUGURE! KOKKURI-SAN",
    "Ga-Rei-Zero",
    "Gabriel DropOut",
    "Gad Guard",
    "Gakkatsu!",
    "Gakuen Alice",
    "Gakuen Basara:Samurai High School",
    "Gakuen Handsome",
    "Gakuen Heaven",
    "Gakuen Utopia Manabi Straight!",
    "Gal & Dino",
    "Galaxy Angel",
    "Galaxy Angel 3",
    "Galaxy Angel 4",
    "Galaxy Angel Rune",
    "Galaxy Angel Z",
    "Galaxy Warring State Chronicle Rai",
    "Galilei Donna:Storia di tre sorelle a caccia di un mistero",
    "Gallery Fake",
    "Gamers!",
    "Gangsta.",
    "Gankutsuou:The Count of Monte Cristo",
    "Gantz",
    "Gantz:Second Stage",
    "Gargantia on the Verdurous Planet",
    "Gargoyle of Yoshinaga House",
    "Garo:Crimson Moon",
    "Gasaraki",
    "Gatchaman",
    "Gatchaman Crowds",
    "Gatchaman Crowds Insight",
    "Gate Keepers",
    "GeGeGe no Kitaro",
    "Generator Gawl",
    "Geneshaft",
    "Genshiken",
    "Genshiken 2",
    "Genshiken Second Season",
    "Getbackers",
    "Getsumen To Heiki Mina",
    "Ghastly Prince Enma Burning Up",
    "Ghost Hound",
    "Ghost Hunt",
    "Ghost Slayers Ayashi",
    "Ghost Stories",
    "Ghost in the Shell:Arise - Alternative Architecture",
    "Ghost in the Shell:Stand Alone Complex",
    "Ghost in the Shell:Stand Alone Complex 2nd GIG",
    "Ghost in the Shell:Stand Alone Complex:Tachikomatic Days",
    "Giant Killing",
    "Gibiate",
    "Gift: Eternal Rainbow",
    "Gifuu Doudou!!: Kanetsugu to Keiji",
    "Gilgamesh",
    "Ginga Nagareboshi Gin",
    "Ginga Tetsudou 999",
    "Ginga e Kickoff!!",
    "Gingitsune:Messenger Fox of the Gods",
    "Giniro no Olynsis: Tokito",
    "Gintama",
    "Gintama Season 2",
    "Gintama Season 4",
    "Gintama Season 5",
    "Gintama.:Silver Soul Arc",
    "Gintama.:Silver Soul Arc - Second Half War",
    "Gintama.:Slip Arc",
    "Gintama:Enchousen",
    "Ginyuu Mokushiroku Meine Liebe",
    "Girl Friend Beta",
    "Girl Meets Girl",
    "Girlish Number",
    "Girls & Panzer",
    "Girls Beyond the Wasteland",
    "Girls Bravo",
    "Girls Bravo:Second Season",
    "Girls' Last Tour",
    "Girly Air Force",
    "Given",
    "Glass Fleet:The Legend of the Wind of the Universe",
    "Glass Maiden",
    "Glass Mask",
    "Glass no Kamen",
    "Glasslip",
    "Gleipnir",
    "Glitter Force",
    "Glitter Force Doki Doki",
    "Go! Go! 575",
    "Go! Princess Precure",
    "Goblin Slayer",
    "God Eater",
    "Gokudo",
    "Gokujo.: Gokurakuin Joshikou Ryou Monogatari",
    "Golden Kamuy",
    "Golden Kamuy Season 3",
    "Golden Kamuy:Season 2",
    "Golden Time",
    "Golgo 13",
    "Gonna be the Twin-Tail!!",
    "Good Luck Girl!",
    "Good Luck! Ninomiya-kun",
    "Gosick",
    "Gourmet Girl Graffiti",
    "Granbelm",
    "Granblue Fantasy The Animation",
    "Grand Blue Dreaming",
    "Grand Blues!",
    "Grappler Baki (TV)",
    "Grappler Baki: Saidai Tournament-hen",
    "Graveyard Kitaro",
    "Gravitation",
    "Great Teacher Onizuka",
    "Green Green",
    "Grenadier:The Beautiful Warrior",
    "Grimgar:Ashes and Illusions",
    "Grimms Notes The Animation",
    "Ground Control to Psychoelectric Girl",
    "Guardian Ninja Mamoru",
    "Guilty Crown",
    "Guin Saga",
    "Gun Frontier",
    "Gun x Sword",
    "Gundam Build Divers",
    "Gundam Build Fighters",
    "Gundam Build Fighters Try",
    "Gundam Reconguista in G",
    "Gungrave",
    "Gunjou no Magmell",
    "Gunparade March:A New Song for the March",
    "Gunslinger Girl",
    "Gunslinger Girl:Il Teatrino",
    "Gunslinger Stratos:The Animation",
    "Gurazeni Season 2",
    "Gurazeni:Money Pitch",
    "Gurren Lagann",
    "H2",
    "H2O:Footprints in the Sand",
    "HIMOTE HOUSE:A share house of super psychic girls",
    "Hackadoll The Animation",
    "Haganai:I don't have many friends",
    "Haganai:I don't have many friends NEXT",
    "Hagane Orchestra",
    "Haha wo Tazunete Sanzenri",
    "Haibane Renmei",
    "Haikyu!!",
    "Haikyu!! 2nd Season",
    "Haikyu!! 3rd Season",
    "Haikyuu!!: To the Top",
    "Haikyuu!!: To the Top 2nd Season",
    "Haitai Nanafa",
    "Haitai Nanafa 2nd Season",
    "Haiyoru! Nyaruani:Remember My Mr. Lovecraft",
    "Hajime No Ippo:The Fighting!",
    "Hakata Mentai! Pirikarako-chan",
    "Hakata Tonkotsu Ramens",
    "Hakkenden -Eight Dogs of the East-",
    "Hakkenden -Eight Dogs of the East- Season 2",
    "Hakone-chan",
    "Hakumei and Mikochi",
    "Hakuoki ~Demon of the Fleeting Blossom~",
    "Hakuoki ~Demon of the Fleeting Blossom~ Dawn of the Shinsengumi",
    "Hakuoki ~Demon of the Fleeting Blossom~ Record of the Jade Blood",
    "Hakuouki: Otogisoushi",
    "Hakyu Hoshin Engi",
    "Hamatora The Animation",
    "Hamtaro",
    "Hana Yori Dango",
    "Hanada Shounen-shi",
    "Hanamaru Kindergarten",
    "Hanamonogatari",
    "Hanasakeru Seishounen",
    "Hanasaku Iroha:Blossoms for Tomorrow",
    "Hanaukyo Maid Team:La Verite",
    "Hanaukyou Maid-tai",
    "Hanayamata",
    "Hand Maid May",
    "Hand Shakers",
    "Handa-kun",
    "Hanebado!",
    "Hanoka",
    "Happiness Charge Precure!",
    "Happiness!",
    "Happy Sugar Life",
    "Happy\u2606Lesson (TV)",
    "Happy\u2606Lesson: Advance",
    "Haruchika:Haruta & Chika",
    "Haruka Nogizaka's Secret",
    "Haruka:Beyond the Stream of Time \u2013 A Tale of the Eight Guardians",
    "Harukana Receive",
    "Har\u00e9+Guu",
    "Hataraki Man",
    "Hatena Illusion",
    "Hatenkou Yugi",
    "Hatsukoi Limited",
    "Haven't You Heard? I'm Sakamoto",
    "Hayate the Combat Butler",
    "Hayate the Combat Butler! Cuties",
    "Hayate the Combat Butler!!",
    "Hayate the Combat Butler:Can't Take My Eyes Off You",
    "He is My Master",
    "Heartcatch Precure!",
    "HeatGuy J",
    "Heaven's Lost Property",
    "Heaven's Lost Property:Forte",
    "Heaven's Memo Pad",
    "Heavy Object",
    "Hell Girl",
    "Hell Girl:Fourth Twilight",
    "Hell Girl:Three Vessels",
    "Hell Girl:Two Mirrors",
    "Hello!! KINMOZA!",
    "Hellsing",
    "HenSemi (TV)",
    "Hensuki:Are you willing to fall in love with a pervert, as long as she's a cutie?",
    "Hentatsu (TV)",
    "Here Comes the Black Witch!!",
    "Hero Tales",
    "Heroic Age",
    "Heroman",
    "Hidamari Sketch",
    "Hidamari Sketch x 365",
    "Hidamari Sketch x Honeycomb",
    "Hidamari Sketch x \u2606\u2606\u2606",
    "Higepiyo",
    "High School DxD",
    "High School DxD BorN",
    "High School DxD Hero",
    "High School DxD New",
    "High School Fleet",
    "High School Girls",
    "High School of the Dead",
    "High Score",
    "High Score Girl",
    "High Score Girl II",
    "Hiiro no Kakera:The Tamayori Princess Saga",
    "Hiiro no Kakera:The Tamayori Princess Saga Season 2",
    "Hikaru no Go",
    "Himawari Too!!",
    "Himawari!",
    "Himegoto",
    "Himouto! Umaru-chan",
    "Himouto! Umaru-chan R",
    "Hina Logic \u2013 from Luck & Logic",
    "Hinako Note",
    "Hinamatsuri",
    "Hinomaru Sumo",
    "Hipira-kun",
    "His and Her Circumstances",
    "Hit wo Nerae!",
    "Hitohira",
    "Hitori no Shita - The Outcast",
    "Hitoribocchi no Marumaru Seikatsu",
    "Hitorijime My Hero",
    "Hi\u2606sCoool! SeHa Girls",
    "Holmes of Kyoto",
    "Honey and Clover",
    "Honey and Clover II",
    "Honobono Log",
    "Honto ni Atta! Reibai Sensei",
    "Hoop Days",
    "Horizon in the Middle of Nowhere",
    "Horizon in the Middle of Nowhere II",
    "House of Five Leaves",
    "How Not to Summon a Demon Lord",
    "How clumsy you are, Miss Ueno.",
    "How heavy are the dumbbells you lift?",
    "How to Keep a Mummy",
    "Hozuki's Coolheadedness",
    "Hozuki's Coolheadedness 2",
    "Hug tto! Precure",
    "Hulaing Babies",
    "Humanity Has Declined",
    "Hundred",
    "Hungry Heart: Wild Striker",
    "Hungry Zombie Francesca",
    "Hunter x Hunter",
    "Hyakko",
    "Hybrid x Heart Magias Academy Ataraxia",
    "Hyouge Mono",
    "Hyouka",
    "Hyper Police",
    "Hyperdimension Neptunia",
    "Hypnosis Mic: Division Rap Battle - Rhyme Anima",
    "I Can't Understand What My Husband Is Saying",
    "I Can't Understand What My Husband Is Saying:2nd Thread",
    "I My Me! Strawberry Eggs",
    "I'm Gonna Be an Angel!",
    "I'm glad I could keep running.",
    "I'm standing on 1,000,000 lives.",
    "ID-0",
    "ID:INVADED",
    "IDOLM@STER Xenoglossia",
    "IDOLiSH7",
    "IGPX:Immortal Grand Prix",
    "Idol Incidents",
    "Idol Memories",
    "Ie Naki Ko",
    "If Her Flag Breaks",
    "If I See You in My Dreams",
    "If My Favorite Pop Idol Made It to the Budokan, I Would Die",
    "If it's for My Daughter, I'd Even Defeat a Demon Lord",
    "Igano Kabamaru",
    "Ikebukuro West Gate Park",
    "Ikemen Sengoku:Bromances Across Time",
    "Iketeru Futari",
    "Ikki Tousen",
    "Ikkitousen: Great Guardians",
    "Ikkitousen: Xtreme Xecutor",
    "Ikkitousen:Dragon Destiny",
    "In Another World With My Smartphone",
    "In Search of the Lost Future",
    "In/Spectre",
    "Inari Kon Kon",
    "Inazuma Eleven",
    "Inazuma Eleven Go",
    "Inazuma Eleven Go: Chrono Stone",
    "Inazuma Eleven Go: Galaxy",
    "Infini-T Force",
    "Infinite Dendrogram",
    "Infinite Ryvius",
    "Infinite Stratos",
    "Infinite Stratos 2",
    "Initial D Fifth Stage",
    "Initial D Final Stage",
    "Initial D First Stage",
    "Initial D Fourth Stage",
    "Initial D Second Stage",
    "Innocent Venus",
    "Insufficient Direction",
    "Interspecies Reviewers",
    "Interviews With Monster Girls",
    "Inu X Boku Secret Service",
    "InuYasha",
    "InuYasha:The Final Act",
    "Inugami-san to Nekoyama-san",
    "Inukami!",
    "Inuyashiki:Last Hero",
    "Invaders of the Rokujyoma!?",
    "Ippatsu Kiki Musume",
    "Iroduku:The World in Colors",
    "Iron Man",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon?",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? II",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? III",
    "Is This a Zombie?",
    "Is the Order a Rabbit?",
    "Is the Order a Rabbit? Bloom",
    "Is the Order a Rabbit??",
    "Is this A Zombie? of the Dead",
    "Isekai Cheat Magician",
    "Isekai Quartet",
    "Isekai Quartet 2",
    "Ishida & Asakura",
    "Island",
    "Isuca",
    "ItaKiss",
    "Iwa Kakeru!: Sport Climbing Girls",
    "Ixion Saga DT",
    "Izetta:The Last Witch",
    "Izumo:Flash of a Brave Sword",
    "JINSEI -Life Consulting-",
    "JK-MESHI!",
    "JOKER",
    "JOKER 2nd Season",
    "JOKER 3rd Season",
    "JOKER 4th Season",
    "Jigoku Sensei Nube",
    "Jing:King of Bandits",
    "Jingai-san no Yome",
    "Jinki:Extend",
    "JoJo's Bizarre Adventure",
    "JoJo's Bizarre Adventure:Diamond is Unbreakable",
    "JoJo's Bizarre Adventure:Golden Wind",
    "JoJo's Bizarre Adventure:Stardust Crusaders",
    "JoJo's Bizarre Adventure:Stardust Crusaders - Battle in Egypt",
    "Joker Game",
    "Jormungand",
    "Jormungand Season 2:Perfect Order",
    "Joshi Kausei",
    "Joshiochi!: 2-kai kara Onnanoko ga... Futtekita!?",
    "Joshiraku",
    "Jubei-chan 2:The Counterattack of Siberia Yagyu",
    "Jubei-chan the Ninja Girl:Secret of the Lovely Eyepatch",
    "Juden Chan Recharged",
    "Juni Taisen:Zodiac War",
    "Junjo Romantica",
    "Junjo Romantica 2",
    "Junjo Romantica 3",
    "Just Because!",
    "Juuou Mujin no Fafnir",
    "Juusou Kikou Dancougar Nova",
    "Jyu-Oh-Sei:Planet of the Beast King",
    "K",
    "K-ON!",
    "K-ON! Season 2",
    "K:Return of Kings",
    "KADO:The Right Answer",
    "KILL la KILL",
    "KINMOZA!",
    "Kabaneri of the Iron Fortress",
    "Kabukibu!",
    "Kagewani",
    "Kagewani -II-",
    "Kaguya-sama:Love is War",
    "Kaguya-sama:Love is War Season 2",
    "Kaiba",
    "Kaidan Restaurant",
    "Kaiji:Against All Rules",
    "Kaiji:Ultimate Survivor",
    "Kaijuu Girls: Ultra Kaijuu Gijinka Keikaku 2nd Season",
    "Kaikan Phrase",
    "Kaitou Reinya",
    "Kakegurui:Compulsive Gambler",
    "Kakegurui\u00d7\u00d7",
    "Kakuriyo:Bed and Breakfast for Spirits",
    "Kakushigoto",
    "Kakyusei 2",
    "Kaleido Star",
    "Kamen no Maid Guy",
    "Kamichama Karin",
    "Kamichu!",
    "Kamigami no Asobi",
    "Kamikaze Kaitou Jeanne",
    "Kamisama Dolls",
    "Kamisama Kazoku",
    "Kamisama Kiss",
    "Kamisama Kiss Season 2",
    "KanColle:Kantai Collection",
    "Kanamemo",
    "Kandagawa Jet Girls",
    "Kannagi:Crazy Shrine Maidens",
    "Kanojo to Kanojo no Neko: Everything Flows",
    "Kanokon:The Girl Who Cried Fox",
    "Kanon",
    "Karakai Jouzu no Takagi-san 2",
    "Karakurizoushi Ayatsuri Sakon",
    "Karin",
    "Karneval",
    "Katana Maidens:Toji no Miko",
    "Katanagatari",
    "Katsugeki Touken Ranbu",
    "Kaze no Stigma",
    "Kaze no Yojimbo",
    "Keep Your Hands Off Eizouken!",
    "Keijo!!!!!!!!",
    "Kekkaishi",
    "Kemeko Deluxe!",
    "Kemono Friends",
    "Kemono Friends 2",
    "Kemono Michi:Rise Up",
    "Kemonozume",
    "Kemurikusa (TV)",
    "KenIchi:The Mightiest Disciple",
    "Kenka Bancho Otome -Girl Beats Boys-",
    "Kenkou Zenrakei Suieibu Umishou",
    "Ketsuekigata-kun!",
    "Ketsuekigata-kun! 2",
    "Ketsuekigata-kun! 3",
    "Ketsuekigata-kun! 4",
    "Kiba",
    "Kiddy Girl-AND",
    "Kiddy Grade",
    "Kids on the Slope",
    "Kiitaro's yokai picture diary",
    "Kill Me Baby",
    "Killing Bites",
    "Kimagure Orange\u2606Road",
    "Kimagure Robot",
    "Kimi ga Aruji de Shitsuji ga Ore de",
    "Kimi ni Todoke:From Me To You 2",
    "Kimi ni Todoke:From Me to You",
    "KimiKiss:Pure Rouge",
    "Kindaichi Shounen no Jikenbo",
    "Kindaichi Shounen no Jikenbo Returns 2nd Season",
    "King From Now On!",
    "King of Braves GaoGaiGar",
    "King's Game",
    "Kingdom",
    "Kingdom:Season 2",
    "Kino's Journey",
    "Kino's Journey -the Beautiful World- the Animated Series",
    "Kirakira\u2606Precure A La Mode",
    "Kirby:Right Back at Ya!",
    "Kishin Houkou Demonbane (TV)",
    "Kishin Taisen Gigantic Formula",
    "Kiss Dum: Engage Planet",
    "Kiss Him, Not Me!",
    "Kiss x Sis (TV)",
    "Kiznaiver",
    "Knight Hunters",
    "Knight Hunters Eternity",
    "Knight's & Magic",
    "Knights of Sidonia",
    "Knights of Sidonia:Battle for Planet Nine",
    "Kobato.",
    "KochinPa!",
    "Kochoki",
    "Kodocha",
    "Kodomo no Jikan (TV)",
    "Koi Kaze",
    "Koi Koi Seven",
    "Koihime\u2020Musou",
    "Kokkoku",
    "Kokoro Connect",
    "Kokoro Toshokan",
    "Komori-san Can't Decline!",
    "Kono Aozora ni Yakusoku wo: Youkoso Tsugumi Ryou e",
    "Kono Oto Tomare!:Sounds of Life",
    "Kono Oto Tomare!:Sounds of Life Season 2",
    "KonoSuba:God's Blessing on This Wonderful World!",
    "KonoSuba:God's Blessing on This Wonderful World! 2",
    "Konohana Kitan",
    "Koroshiya-san: The Hired Gun",
    "Koukaku Kidoutai Nyuumon Arise",
    "Kowabon",
    "Kujibiki\u2665Unbalance",
    "Kuma Kuma Kuma Bear",
    "Kumamiko:Girl Meets Bear",
    "Kurau Phantom Memory",
    "Kurayami Santa",
    "Kurenai",
    "Kurokami The Animation",
    "Kuroko's Basketball",
    "Kuroko's Basketball 2",
    "Kuroko's Basketball 3",
    "Kuromukuro",
    "Kurozuka",
    "Kyou kara Maou! 3rd Series",
    "Kyou no 5 no 2 (TV)",
    "Kyouran Kazoku Nikki",
    "Kyoushoku Soukou Guyver (2005)",
    "Kyousougiga",
    "K\u00e4mpfer",
    "La corda d'oro:Blue\u266aSky",
    "La corda d'oro:primo passo",
    "La storia della Arcana Famiglia",
    "Ladies versus Butlers!",
    "Ladyspo",
    "Lagrange:The Flower of Rin-ne",
    "Lagrange:The Flower of Rin-ne Season 2",
    "Laid-Back Camp",
    "Lamune",
    "Lance N' Masques",
    "Land of the Lustrous",
    "Lapis Re:LiGHTs",
    "Last Exile",
    "Last Exile:Fam, the Silver Wing",
    "Last Hope",
    "Last Period:The Journey to the End of the Despair",
    "Laughing Under the Clouds",
    "Layton Mystery Tanteisha: Katri no Nazotoki File",
    "Le Chevalier D'Eon",
    "Le Cirque de Karakuri",
    "Legend of Basara",
    "Legend of Black Heaven",
    "Legend of Duo",
    "Legend of Himiko",
    "Legend of the Galactic Heroes:Die Neue These",
    "Legends of the Dark King:A Fist of the North Star Story",
    "Lemon Angel Project",
    "Les Mis\u00e9rables: Shoujo Cosette",
    "Let's Nupu Nupu",
    "Level E",
    "Leviathan:The Last Defense",
    "Libra of Nil Admirari",
    "Library Wars",
    "Lime-iro Senkitan",
    "Linebarrels of Iron",
    "Listen to Me, Girls. I Am Your Father!",
    "Listeners",
    "Little Busters!",
    "Little Busters! ~Refrain~",
    "Little Witch Academia",
    "Living for the Day After Tomorrow",
    "Locodol",
    "Log Horizon",
    "Log Horizon 2",
    "Long Riders!",
    "Looking Up At The Half-Moon",
    "Lord El-Melloi II Sei no Jikenbo: Rail Zeppelin Grace Note",
    "Lord Marksman and Vanadis",
    "Lord of Vermilion:The Crimson King",
    "Lost Song",
    "Lost Universe",
    "Lostorage Conflated WIXOSS",
    "Lostorage incited WIXOSS",
    "Love Hina",
    "Love Lab",
    "Love Live! Nijigasaki Gakuen School Idol Doukoukai",
    "Love Live! School Idol Project",
    "Love Live! School Idol Project 2",
    "Love Live! Sunshine!!",
    "Love Live! Sunshine!! Season 2",
    "Love Rice",
    "Love Rice 2",
    "Love Stage!!",
    "Love To-LIE-Angle",
    "Love Tyrant",
    "Love and Lies",
    "Love is Like a Cocktail",
    "Love, Chunibyo & Other Delusions!",
    "Love, Chunibyo & Other Delusions!:Heart Throb",
    "Love, Election and Chocolate",
    "Loveless",
    "Lovely Complex",
    "Lovely Idol",
    "Lovely Muuuuuuuco!",
    "Love\u2665Love?",
    "Loving Angel Angelique:Radiant Tomorrow",
    "Loving Angel Angelique:When Hearts Awaken",
    "Luck & Logic",
    "Lucky\u2606Star",
    "Lunar Legend Tsukihime",
    "Lupin III",
    "Lupin III: Part 5",
    "Lupin III: Part II",
    "Lupin III: Part III",
    "Lupin the Third",
    "Lupin the Third, The Woman Called Fujiko Mine",
    "Lychee Light Club",
    "M3: Sono Kuroki Hagane",
    "MAGATSU WAHRHEIT",
    "MARGINAL #4 the Animation",
    "MEGALOBOX",
    "MEKAKUCITY ACTORS",
    "MM!",
    "MUSHI-SHI -Next Passage-",
    "Maburaho",
    "Macademi Wasshoi!",
    "Macross",
    "Macross 7",
    "Macross Delta",
    "Macross Frontier",
    "Madam is a Magical Girl",
    "Made in Abyss",
    "Madlax",
    "Maerchen Maedchen",
    "Maesetsu! Opening Act",
    "Magi:Adventure of Sinbad",
    "Magi:The Kingdom of Magic",
    "Magi:The Labyrinth of Magic",
    "Magia Record:Puella Magi Madoka Magica Side Story",
    "Magic Kaito 1412",
    "Magic Knight Rayearth",
    "Magic Knight Rayearth II",
    "Magic User's Club",
    "Magic of Stella",
    "Magic-Kyun! Renaissance",
    "Magica Wars",
    "Magical Angel Creamy Mami",
    "Magical Circle",
    "Magical Circle Guru Guru",
    "Magical DoReMi",
    "Magical Girl Lyrical Nanoha",
    "Magical Girl Lyrical Nanoha A's",
    "Magical Girl Lyrical Nanoha StrikerS",
    "Magical Girl Ore",
    "Magical Girl Raising Project",
    "Magical Girl Site",
    "Magical Girl Spec-Ops Asuka",
    "Magical Kanan",
    "Magical Meow Meow Taruto",
    "Magical Project S",
    "Magical Sempai",
    "Magical Stage Fancy Lala",
    "Magical Warfare",
    "Magical\u2606Shopping Arcade Abenobashi",
    "Magikano",
    "Magimoji Rurumo",
    "Maho Girls Precure!",
    "Mahoraba: Heartful days",
    "Mahoromatic ~Something More Beautiful~",
    "Mahoromatic:Automatic Maiden",
    "Mahou Shoujo Lyrical Nanoha ViVid",
    "Mahou Shoujo Nante Mouiidesukara",
    "Mahou Shoujo Nante Mouiidesukara Second Season",
    "Mahou Shoujo? Naria Girls",
    "Maid Sama!",
    "Maison Ikkoku",
    "Majestic Prince",
    "Maji de Otaku na English! Ribbon-chan: Eigo de Tatakau Mahou Shoujo",
    "Maji de Otaku na English! Ribbon-chan: Eigo de Tatakau Mahou Shoujo - The TV",
    "Majikoi:Oh! Samurai Girls",
    "Majin Bone",
    "Major 2nd (TV)",
    "Major 2nd (TV) 2nd Season",
    "Major S1",
    "Major S2",
    "Major S3",
    "Major S4",
    "Major S5",
    "Major S6",
    "Maken-Ki!",
    "Maken-Ki! Two",
    "Makeruna!! Aku no Gundan!",
    "Mangirl!",
    "Manyuu Hikenchou",
    "Maoyu ~ Archenemy & Hero",
    "March Comes In Like A Lion 2nd Season",
    "March comes in like a lion",
    "Maria Watches Over Us",
    "Maria Watches Over Us Season 4",
    "Maria Watches Over Us:Printemps",
    "Maria the Virgin Witch",
    "Maria\u2020Holic",
    "Maria\u2020Holic Alive",
    "Marmalade Boy",
    "Marriage of God & Soul Godannar!!",
    "Mars Daybreak",
    "Martian Successor Nadesico",
    "Marvel Disk Wars: The Avengers",
    "Masamune-kun's Revenge",
    "Mashiroiro Symphony:The Color of Lovers",
    "Master Keaton",
    "Masuda Kousuke Gekijou Gag Manga Biyori",
    "Masuda Kousuke Gekijou Gag Manga Biyori 3",
    "Matoi the Sacred Slayer",
    "Maya the Bee",
    "Mayo Chiki!",
    "Mayoi Neko Overrun!",
    "Maze:The Mega-Burst Space",
    "Mazinger Edition Z:The Impact!",
    "Mazinger Z",
    "Medabots",
    "Medabots Spirits",
    "Medaka Box",
    "Medaka Box Abnormal",
    "MegaMan NT Warrior",
    "MegaMan:Axess",
    "Megaman Star Force",
    "Megami Kouhosei",
    "Meganebu!",
    "Meiji Tokyo Renka",
    "Merc StoriA:The Apathetic Boy and the Girl in a Bottle",
    "Mermaid Forest",
    "Mermaid Melody:Pichi Pichi Pitch",
    "Metal Fight Beyblade",
    "Mew Mew Power",
    "Mezzo DSA",
    "Miami Guns",
    "Michiko & Hatchin",
    "Midnight occult civil servants",
    "Midori Days",
    "Mikagura School Suite",
    "Military!",
    "Millennium Old Journal:Tale of Genji",
    "Million Doll",
    "Minami Kamakura High School Girls Cycling Club",
    "Minami-ke",
    "Minami-ke Okaeri",
    "Minami-ke Okawari",
    "Minami-ke Tadaima",
    "Mini Toji",
    "Minna Atsumare! Falcom Gakuen",
    "Minna Atsumare! Falcom Gakuen SC",
    "Miracle Train:Welcome to the Oedo Line",
    "Mirage of Blaze",
    "Misaki Chronicle:Divergence Eve",
    "Miss Bernard said.",
    "Miss Kobayashi's Dragon Maid",
    "Miss Monochrome The Animation",
    "Miss Monochrome The Animation 2",
    "Miss Monochrome The Animation 3",
    "Miss caretaker of Sunohara-sou",
    "Mission-E",
    "Mitchiri Neko",
    "Mitsuboshi Colors",
    "Mitsudomoe",
    "Mitsudomoe Zouryouchuu!",
    "Mix",
    "Mob Psycho 100",
    "Mob Psycho 100 II",
    "Mobile Fighter G Gundam",
    "Mobile Suit Gundam",
    "Mobile Suit Gundam 00",
    "Mobile Suit Gundam 00:Second Season",
    "Mobile Suit Gundam AGE",
    "Mobile Suit Gundam SEED",
    "Mobile Suit Gundam SEED Destiny",
    "Mobile Suit Gundam Unicorn RE:0096",
    "Mobile Suit Gundam Wing",
    "Mobile Suit Gundam ZZ",
    "Mobile Suit Gundam-san",
    "Mobile Suit Gundam:Iron-Blooded Orphans",
    "Mobile Suit Gundam:Iron-Blooded Orphans 2nd Season",
    "Mobile Suit Gundam:The Origin - Advent of the Red Comet",
    "Mobile Suit V Gundam",
    "Mobile Suit Zeta Gundam",
    "Modern Magic Made Simple",
    "Moetan",
    "Moeyo Ken TV",
    "Mokke",
    "Momo, Girl God of Death",
    "Momokyun Sword",
    "Monochrome Factor",
    "Monogatari Series:Second Season",
    "Mononoke",
    "Monster",
    "Monster Girl Doctor",
    "Monster Musume:Everyday Life with Monster Girls",
    "Monster Rancher",
    "Monster Rancher (2000)",
    "Monthly Girls' Nozaki-kun",
    "Moonlight Mile 1st Season: Lift Off",
    "Moonlight Mile 2nd Season: Touch Down",
    "More! Useless Witch Doremi",
    "Moriarty the Patriot",
    "Moribito - Guardian of the Spirit",
    "Morita-san wa Mukuchi.",
    "Morita-san wa Mukuchi. 2",
    "Moshidora",
    "Motto To LOVE Ru",
    "Mouryou no Hako",
    "Mouse",
    "Moyashimon",
    "Moyashimon Returns",
    "Mr Love:Queen's Choice",
    "Mr. Osomatsu",
    "Mr. Osomatsu 2",
    "Mr. Tonegawa:Middle Management Blues",
    "Ms. Koizumi Loves Ramen Noodles",
    "Ms. vampire who lives in my neighborhood.",
    "Muhyo & Roji's Bureau of Supernatural Investigation",
    "Muhyo & Roji's Bureau of Supernatural Investigation 2nd Season",
    "Mujin Wakusei Survive",
    "Munou na Nana",
    "Muromi-san",
    "Mushi-Shi",
    "Mushi-Uta",
    "Mushibugyo",
    "Mushishi Zoku Shou 2nd Season",
    "Music Girls",
    "Muv-Luv Alternative:Total Eclipse",
    "My Bride is a Mermaid",
    "My Daddy Long Legs",
    "My First Girlfriend is a Gal",
    "My Girlfriend is Shobitch",
    "My Hero Academia",
    "My Hero Academia 2",
    "My Hero Academia 3",
    "My Hero Academia 4",
    "My Little Monster",
    "My Love Story!!",
    "My Mental Choices Are Completely Interfering With My School Romantic Comedy",
    "My Next Life as a Villainess:All Routes Lead to Doom!",
    "My Roommate is a Cat",
    "My Sister, My Writer",
    "My Sweet Tyrant",
    "My Teen Romantic Comedy SNAFU",
    "My Teen Romantic Comedy SNAFU Climax!",
    "My Teen Romantic Comedy SNAFU TOO!",
    "My Wife is a High School Girl",
    "My Wife is the Student Council President!",
    "My Wife is the Student Council President!+",
    "My-Hime",
    "My-Otome",
    "Myriad Colors Phantom World",
    "Myself; Yourself",
    "Mysteria Friends",
    "Mysterious Girlfriend X",
    "Mysterious Play",
    "Mysterious Thief Saint Tail",
    "Mythical Detective Loki Ragnarok",
    "M\u00c4R",
    "NAKAIMO - My Little Sister Is Among Them!",
    "NAMUAMIDABUTSU! -UTENA-",
    "NARUTO Spin-Off:Rock Lee & His Ninja Pals",
    "Nabari no Ou",
    "Nadia:Secret of Blue Water",
    "Nagasarete Airantou",
    "Najica Blitz Tactics",
    "Nana",
    "Nanaka 6/17",
    "Nanana's Buried Treasure",
    "Nanatsu-iro\u2605Drops",
    "Nanbaka",
    "Nande Koko ni Sensei ga!?",
    "Naruto",
    "Naruto:Shippuden",
    "Natsu no Arashi!",
    "Natsu-iro Kiseki",
    "Natsume's Book of Friends",
    "Natsume's Book of Friends Season 2",
    "Natsume's Book of Friends Season 3",
    "Natsume's Book of Friends Season 4",
    "Natsume's Book of Friends Season 5",
    "Natsume's Book of Friends Season 6",
    "Natsunagu!",
    "Natsuyuki Rendezvous",
    "Nazotokine",
    "Needless",
    "Negima!",
    "Negima!? Magister Negi Magi",
    "Neighborhood Stories",
    "Nekojiru Gekijou Jirujiru Original",
    "Nekomonogatari Black",
    "NekoparA",
    "Neo Angelique Abyss",
    "Neo Angelique Abyss: Second Age",
    "Neo Ranga",
    "Neon Genesis Evangelion",
    "Netsuzou Trap -NTR-",
    "Neuro:Supernatural Detective",
    "New Game!",
    "New Game!!",
    "Nichijou - My Ordinary Life",
    "NieA Under 7",
    "Night Head Genesis",
    "Night Raid 1931",
    "Night Wizard",
    "Nightwalker:The Midnight Detective",
    "Ninja Collection",
    "Ninja Girl & Samurai Master",
    "Ninja Girl & Samurai Master 2nd",
    "Ninja Girl & Samurai Master:Anegawa and Ishiyama Arc",
    "Ninja Nonsense",
    "Ninja Scroll:The Series",
    "Nisekoi:False Love",
    "Nisemonogatari",
    "No Game, No Life",
    "No Guns Life",
    "No-Rin",
    "No. 6",
    "Noblesse",
    "Nobunaga Concerto",
    "Nobunaga teacher's young bride",
    "Nobunaga the Fool",
    "Nobunagun",
    "Nodame Cantabile",
    "Nodame Cantabile: Finale",
    "Nodame Cantabile: Paris-hen",
    "Noein:to your other self",
    "Nogizaka Haruka no Himitsu: Purezza",
    "Noir",
    "Non Non Biyori",
    "Non Non Biyori Repeat",
    "Nora, Princess, and Stray Cat",
    "Noragami Aragoto",
    "Noragami:Stray God",
    "Norn9",
    "Now and Then, Here and There",
    "Nura:Rise of the Yokai Clan",
    "Nura:Rise of the Yokai Clan - Demon Capital",
    "Nurse Witch Komugi-chan R",
    "Nyan Koi!",
    "Nyanbo!",
    "Nyanko Days",
    "Nyanpire The Animation",
    "Nyaruko:Crawling With Love!",
    "Nyaruko:Crawling With Love! Second Season",
    "O Maidens in Your Savage Season",
    "ORESUKI Are you the only one who loves me?",
    "Oban Star-Racers",
    "Occult Academy",
    "Occultic;Nine",
    "Oda Cinnamon Nobunaga",
    "Oh! Edo Rocket",
    "Oh! My Goddess:The Adventures of Mini-Goddess",
    "Ojamajo Doremi Sharp",
    "Ojisan and Marshmallow",
    "Okami-San and Her Seven Companions",
    "Okamikakushi:Masque of the Wolf",
    "Okko's Inn",
    "Okoshiyasu, Chitose-chan",
    "Omamori Himari",
    "Omiai Aite wa Oshiego, Tsuyoki na, Mondaiji.",
    "Onara Goro",
    "One Outs",
    "One Punch Man",
    "One Punch Man 2nd Season",
    "One Room",
    "One Room Second Season",
    "One Room Third Season",
    "One Week Friends",
    "Oneechan ga Kita",
    "OniAi",
    "Onigiri",
    "Onihei",
    "Oniichan no Koto nanka Zenzen Suki ja Nai n da kara ne!!",
    "Ookami-san wa Taberaretai",
    "Ooya-san wa Shishunki!",
    "Operation Han-Gyaku-Sei Million Arthur",
    "Operation Han-Gyaku-Sei Million Arthur 2nd Season",
    "Orange",
    "Ore no Yubi de Midarero.: Heitengo Futarikiri no Salon de...",
    "OreImo",
    "Oreimo 2",
    "Orenchi no Furo Jijou",
    "Oreshura",
    "Orphen",
    "Orphen 2:Revenge",
    "Oruchuban Ebichu",
    "Otoboku:Maidens are Falling for Me!",
    "Otogi Zoshi:The Legend of Magatama",
    "Our Home's Fox Deity",
    "Our Last Crusade or the Rise of a New World",
    "Our love has always been 10 centimeters apart.",
    "Ouran High School Host Club",
    "Outbreak Company",
    "Outburst Dreamer Boys",
    "Outlaw Star",
    "Over Drive",
    "Overflow",
    "Overlord",
    "Overlord II",
    "Overlord III",
    "Overman King Gainer",
    "Owarimonogatari",
    "Owarimonogatari Second Season",
    "Ozma",
    "Ozmafia!!",
    "Pan de Peace!",
    "Pandora in the Crimson Shell",
    "PandoraHearts",
    "Pani Poni Dash!",
    "Panty & Stocking with Garterbelt",
    "Panyo Panyo Di Gi Charat",
    "Papillon Rose",
    "Paradise Kiss",
    "Paranoia Agent",
    "Parasyte -the maxim-",
    "Pastel Life",
    "Pastel Memories",
    "Patlabor:The Mobile Police - The TV Series",
    "Peace Maker Kurogane",
    "Peach Girl:Super Pop Love Hurricane",
    "Peeping Life TV: Season 1??",
    "Peeping Life:The Perfect Edition",
    "Penguindrum",
    "Persona 4 the Animation",
    "Persona 4 the Golden ANIMATION",
    "Persona 5 The Animation",
    "Persona:Trinity Soul",
    "Pet",
    "Pet Shop of Horrors",
    "Peter Grill and the Philosopher's Time",
    "Petite Princess Yucie",
    "PetoPeto-san",
    "Phantasy Star Online 2 The Animation",
    "Phantasy Star Online 2:Episode Oracle",
    "Phantom in the Twilight",
    "Phantom:Requiem for the Phantom",
    "Phi Brain:Puzzle of God 3",
    "Phi-Brain ~ Puzzle of God",
    "Phi-Brain ~ Puzzle of God:The Orpheus Order",
    "Photo Kano",
    "Piacevole:My Italian Cooking",
    "Piano no Mori (TV) 2nd Season",
    "Piano:The Melody of a Young Girl's Heart",
    "Pikotaro's Lullaby La La By (TV)",
    "Ping Pong the Animation",
    "Pingu in the City",
    "Pita-Ten",
    "Place to Place",
    "Planet With",
    "Planetes",
    "Plastic Memories",
    "Please Teacher!",
    "Please Twins",
    "Please tell me! Galko-chan",
    "Plunderer",
    "Poco's Udon World",
    "Pokemon Chronicles",
    "Pokemon Diamond & Pearl",
    "Pokemon:Advanced",
    "Pok\u00e9mon",
    "Pok\u00e9mon The Series:XY",
    "Pok\u00e9mon the Series:Sun & Moon",
    "Pok\u00e9mon the Series:XYZ",
    "Pok\u00e9mon:Black & White",
    "Pok\u00e9mon:Black & White:Adventures in Unova",
    "Pok\u00e9mon:Black & White:Adventures in Unova and Beyond",
    "Pok\u00e9mon:Black & White:Rival Destinies",
    "Polar Bear Cafe",
    "Polyphonica",
    "Polyphonica Crimson S",
    "Pop Team Epic",
    "Popee the Clown",
    "Popotan",
    "Potemayo",
    "Power Stone",
    "Powerpuff Girls Z",
    "Poyopoyo",
    "Pretty Cure",
    "Pretty Cure Max Heart",
    "Pretty Cure:Splash Star",
    "Pretty Guardian Sailor Moon Crystal Season III",
    "Pretty Rhythm: Aurora Dream",
    "Pretty Rhythm: Dear My Future",
    "Pretty Rhythm: Rainbow Live",
    "PriPara",
    "Prince of Stride:Alternative",
    "Princess Connect! Re:Dive",
    "Princess Jellyfish",
    "Princess Lover!",
    "Princess Nine",
    "Princess Princess",
    "Princess Principal",
    "Princess Resurrection",
    "Princess Tutu",
    "Prism Ark",
    "Prison School",
    "Problem children are coming from another world, aren't they?",
    "Project ARMS",
    "Project ARMS:The 2nd Chapter",
    "Protect Me, Heavenly Moon Guardian!",
    "Pr\u00e9tear:The New Legend of Snow White",
    "Psychic Academy",
    "Psychic Detective Yakumo",
    "Psychic Squad",
    "Psycho-Pass",
    "Psycho-Pass 2",
    "Psycho-Pass 3",
    "Pucca",
    "Puella Magi Madoka Magica",
    "Pugyuru",
    "Pumpkin Scissors",
    "Punch Line",
    "Pupa",
    "Pupipo!",
    "Qualidea Code",
    "Queen's Blade: Rebellion",
    "Queen's Blade:Inheritor of the Throne",
    "Queen's Blade:The Exiled Virgin",
    "R-15",
    "R.O.D -The TV-",
    "RADIANT Season 2",
    "RD Sennou Chousashitsu",
    "RE-KAN!",
    "RErideD:Derrida, who leaps through time",
    "RIN-NE",
    "Radiant",
    "Rage of Bahamut:Genesis",
    "Rage of Bahamut:Virgin Soul",
    "Ragnarok the Animation",
    "Ragnastrike Angels",
    "RahXephon",
    "Rail Romanesque",
    "Rail Wars!",
    "Rainbow",
    "Rainbow Days",
    "Rainy Cocoa",
    "Rainy Cocoa in Hawaii",
    "Rainy Cocoa, Welcome to Rainy Color",
    "Ramen Fighter Miki",
    "Rampo Kitan:Game of Laplace",
    "Ranma \u00bd",
    "Rascal Does Not Dream of Bunny Girl Senpai",
    "Rave Master",
    "Ray The Animation",
    "Re:CREATORS",
    "Re:Hamatora:Season 2",
    "Re:Stage! Dream Days\u266a",
    "Re:ZERO -Starting Life in Another World-",
    "Re:ZERO -Starting Life in Another World- Season 2",
    "ReLIFE",
    "Real Girl",
    "Reborn!",
    "Rec",
    "Recently, my sister is unusual.",
    "Record of Grancrest War",
    "Record of Lodoss War:Chronicles of the Heroic Knight",
    "Recorder and Randsell",
    "Recorder and Randsell Mi",
    "Recorder and Randsell Re",
    "Red Data Girl",
    "Red Garden",
    "Red Riding Hood Chacha",
    "Regalia:The Three Sacred Stars",
    "Reideen",
    "Reign:The Conqueror",
    "Reikenzan: Eichi e no Shikaku",
    "Reikenzan: Hoshikuzu-tachi no Utage",
    "Release the Spyce",
    "Renkin San-kyuu Magical? Pokaan",
    "Rent-a-Girlfriend",
    "Rental Magica",
    "Requiem from the Darkness",
    "Restaurant to Another World",
    "Revolutionary Girl Utena",
    "Revue Starlight",
    "Rewrite",
    "Rewrite:Moon and Terra",
    "Riddle Story of Devil",
    "Ride Back",
    "Rin:Daughters of Mnemosyne",
    "Rinshi!! Ekodachan",
    "Rio - Rainbow Gate!:Reshuffle",
    "Ristorante Paradiso",
    "Rizelmine",
    "Ro-Kyu-Bu ~ Fast Break!",
    "Ro-Kyu-Bu! SS",
    "RobiHachi",
    "RoboMasters the Animated Series",
    "Robotics;Notes",
    "Rocket Girls",
    "Rocky Joe 2",
    "Rokka:Braves of the Six Flowers",
    "Romeo and the Black Brothers",
    "Romeo x Juliet",
    "Ronin Warriors",
    "Ronja R\u00f6vardotter",
    "Room Camp",
    "Room Mate",
    "Rosario + Vampire",
    "Rosario + Vampire Capu2",
    "Rowdy Sumo Wrestler Matsutaro!!",
    "Rozen Maiden",
    "Rozen Maiden:Tr\u00e4umend",
    "Rozen Maiden:Zur\u00fcckspulen",
    "Rumbling Hearts",
    "Rumiko Takahashi Anthology",
    "Run with the Wind",
    "Rune Soldier",
    "Rurouni Kenshin",
    "Ryoko's Case File",
    "SD Gundam Force",
    "SD Gundam Sangokuden Brave Battle Warriors",
    "SENGOKUCHOJYUGIGA",
    "SERVAMP",
    "SHIMONETA:A Boring World Where the Concept of Dirty Jokes Doesn't Exist",
    "SHOW BY ROCK!! Mashumairesh!!",
    "SKET Dance",
    "SSSS.Gridman",
    "SUPER HXEROS",
    "Sabagebu! -Survival Game Club!-",
    "Saber Marionette J",
    "Saber Marionette J to X",
    "Sacred Seven",
    "Sadamitsu the Destroyer",
    "Saekano:How to Raise a Boring Girlfriend",
    "Saekano:How to Raise a Boring Girlfriend .flat",
    "Sagrada Reset",
    "Sailor Moon",
    "Sailor Moon R",
    "Sailor Moon S",
    "Sailor Moon Sailor Stars",
    "Sailor Moon SuperS",
    "Saint Beast: Seijuu Kourin-hen",
    "Saint Seiya Omega",
    "Saint Seiya:Knights of the Zodiac",
    "Saiyuki",
    "Saiyuki Gunlock",
    "Saiyuki Reload",
    "Saiyuki Reload Blast",
    "Saki",
    "Saki Episode of Side A",
    "Saki:The Nationals",
    "Sakura Quest",
    "Sakura Trick",
    "Sakura Wars",
    "Sakura Wars the Animation",
    "Salaryman Kintarou",
    "Samurai 7",
    "Samurai Bride",
    "Samurai Champloo",
    "Samurai Deeper Kyo",
    "Samurai Flamenco",
    "Samurai Girl Real Bout High School",
    "Samurai Girls",
    "Samurai Gun",
    "Samurai Harem",
    "Samurai Jam -Bakumatsu Rock-",
    "Samurai Pizza Cats",
    "Sands of Destruction",
    "Sankarea:Undying Love",
    "Sanrio Boys",
    "Sans Famille",
    "Sarazanmai",
    "Sasami Magical Girls Club",
    "Sasami-san@Ganbaranai",
    "Say \"I Love You\".",
    "Sayonara, Zetsubou-Sensei",
    "Scared Rider Xechs",
    "School Babysitters",
    "School Days",
    "School Rumble",
    "School Rumble 2nd Semester",
    "School-Live!",
    "Schoolgirl Strikers: Animation Channel",
    "Schwarzes Marken",
    "Sci-fi Harry",
    "Scorched Bread",
    "Scorching Ping Pong Girls",
    "Scrapped Princess",
    "Scum's Wish",
    "Searching for the Full Moon",
    "Seiren",
    "Seitokai Yakuindomo",
    "Seitokai Yakuindomo*",
    "Seiyu's Life!",
    "Sekai Ichi Hatsukoi - World's Greatest First Love",
    "Sekai Ichi Hatsukoi - World's Greatest First Love 2",
    "Sekirei",
    "Sekirei:Pure Engagement",
    "Sekko Boys",
    "Sengoku BASARA:End of Judgement",
    "Sengoku Basara:Samurai Kings",
    "Sengoku Basara:Samurai Kings 2",
    "Sengoku Collection",
    "Sengoku Musou",
    "Sengoku Night Blood",
    "Senki Zesshou Symphogear AXZ",
    "Senki Zesshou Symphogear XV",
    "Senran Kagura:Ninja Flash",
    "Senran Kagura:Shinovi Master",
    "Senryu Girl",
    "Senyuu.",
    "Senyuu. 2",
    "Seraph of the End:Battle in Nagoya",
    "Seraph of the End:Vampire Reign",
    "Serial Experiments Lain",
    "Servant x Service",
    "Seton Academy:Join the Pack!",
    "Seven Mortal Sins",
    "Seven Senses of the Re'Union",
    "Sexy Commando Gaiden: Sugoi yo!! Masaru-san",
    "Sgt. Frog",
    "Shachibato! President, It's Time for Battle!",
    "Shadow Skill: Eigi",
    "Shadow Star Narutaru",
    "Shakugan no Shana:Season I",
    "Shakugan no Shana:Season II",
    "Shakugan no Shana:Season III",
    "Shaman King",
    "Shangri-La",
    "Shattered Angels",
    "She, The Ultimate Weapon",
    "Sherlock Hound",
    "Shiba Inuko-san",
    "Shigofumi:Letters from the Departed",
    "Shigurui:Death Frenzy",
    "Shiki",
    "Shin Chuuka Ichiban!",
    "Shin Koihime\u2020Musou",
    "Shin Koihime\u2020Musou: Otome Tairan",
    "Shin Strange+",
    "Shining Hearts: Shiawase no Pan",
    "Shining Tears X Wind",
    "Shinkon Gattai Godannar!! 2nd Season",
    "Shinya! Tensai Bakabon",
    "Shinzo",
    "Shion no Ou",
    "Shirobako",
    "Shironeko Project ZERO CHRONICLE",
    "Shokupan Mimi",
    "Shomin Sample",
    "Shonen Maid",
    "Shonen Onmyoji",
    "Shoubushi Densetsu Tetsuya",
    "Shounen Ashibe: Go! Go! Goma-chan",
    "Shounen Hollywood: Holly Stage for 49",
    "Shounen Hollywood: Holly Stage for 50",
    "Show By Rock!!",
    "Show By Rock!! 2",
    "Show By Rock!! Short!!",
    "Showa Genroku Rakugo Shinju",
    "Shrine of the Morning Mist",
    "Shuffle!",
    "Shuffle! Memories",
    "Shugo Chara!",
    "Shugo Chara! Party!",
    "Shugo Chara!! Doki",
    "Shuudengo, Capsule Hotel de, Joushi ni Binetsu Tsutawaru Yoru.",
    "Silent M\u00f6bius",
    "Silver Spoon",
    "Silver Spoon 2nd Season",
    "Simoun",
    "Sing \"Yesterday\" for Me",
    "Sirius the Jaeger",
    "Sister Princess",
    "Sister Princess: Re Pure",
    "Sisters of Wellber Zwei",
    "Skating Rink Kaleidoscope",
    "Sketchbook ~full color's~",
    "Skip Beat!",
    "Skirt no Naka wa Kedamono Deshita.",
    "Skull-face Bookseller Honda-san",
    "Sky Girls",
    "Sky Wizards Academy",
    "Slam Dunk",
    "Slayers",
    "Slayers Evolution-R",
    "Slayers Next",
    "Slayers Revolution",
    "Slayers Try",
    "Sleepy Princess in the Demon Castle",
    "Slow Start",
    "Smile Down the Runway",
    "Snow White with the Red Hair",
    "Snow White with the Red Hair 2",
    "So, I Can't Play H!",
    "Softenni! the Animation",
    "Sola",
    "Solty Rei",
    "Somali and the Forest Spirit",
    "Someday's Dreamers",
    "Someday's Dreamers II:Sora",
    "Soni-Ani:Super Sonico The Animation",
    "Sonic X",
    "Sono Toki, Kanojo wa.",
    "Sora wo Miageru Shoujo no Hitomi ni Utsuru Sekai",
    "Sorcerer Hunters",
    "Sorcerous Stabber Orphen",
    "Soukyuu no Fafner: Dead Aggressor - Exodus",
    "Soukyuu no Fafner: Dead Aggressor - Exodus 2nd Season",
    "Soul Buster",
    "Soul Eater",
    "Soul Eater NOT!",
    "Soul Hunter",
    "Soul Link",
    "SoulTaker",
    "Sound of the Sky",
    "Sound! Euphonium",
    "Sound! Euphonium 2",
    "Souryo to Majiwaru Shikiyoku no Yoru ni...",
    "Space Adventure Cobra",
    "Space Battleship Tiramisu",
    "Space Battleship Tiramisu Zwei",
    "Space Brothers",
    "Space Dandy",
    "Space Dandy 2nd Season",
    "Space Patrol Luluco",
    "Space Pirate Captain Harlock",
    "Space Runaway Ideon",
    "Sparrow's Hotel",
    "Special 7:Special Crime Investigation Unit",
    "Special A (S.A)",
    "Speed Grapher",
    "Speed Racer",
    "Spice and Wolf",
    "Spice and Wolf II",
    "Spiral:Bond of Reasoning",
    "Spiritpact:Bond of the Underworld",
    "Stand My Heroes:Piece of Truth",
    "Star Blazers:The Bolar Wars",
    "Star Blazers:The Comet Empire",
    "Star Blazers:The Quest for Iscandar",
    "Star Driver",
    "Star Ocean EX",
    "Starmyu",
    "Starmyu 2nd Season",
    "Starmyu 3rd Season",
    "Stars Align",
    "Starship Operators",
    "Steel Angel Kurumi",
    "Steel Angel Kurumi 2",
    "Steins;Gate",
    "Steins;Gate 0",
    "Stella Women's Academy, High School Division Class C\u00b3",
    "Stellvia",
    "Strain:Strategic Armored Infantry",
    "Strange+",
    "Stratos 4",
    "Strawberry 100%",
    "Strawberry Marshmallow",
    "Strawberry Panic",
    "Street Fighter II:The Animated Series",
    "Strike Witches",
    "Strike Witches 2",
    "Strike Witches: Road to Berlin",
    "Strike Witches:501st JOINT FIGHTER WING Take Off!",
    "Strike the Blood",
    "Student Council's Discretion",
    "Sugar Sugar Rune",
    "Suite Precure\u266a",
    "Sukisho",
    "Summer Storm! Open for Business",
    "Sumomomo Momomo: Chijou Saikyou no Yome",
    "Sunday Without God",
    "Super GALS!",
    "Super Heavy God Gravion",
    "Super Heavy God Gravion Zwei",
    "Super Lovers",
    "Super Lovers 2",
    "Super Robot Wars OG:The Inspector",
    "Super Robot Wars The Original Generation:The Divine Wars",
    "Super Seisyun Brothers",
    "Sushi Police",
    "Suzakinishi The Animation",
    "Suzuka",
    "Sweet Blue Flowers",
    "Sweet Valerian",
    "Sweetness & Lightning",
    "Sword Art Online",
    "Sword Art Online Alicization War of Underworld",
    "Sword Art Online Alicization War of Underworld Part 2",
    "Sword Art Online Alternative: Gun Gale Online",
    "Sword Art Online II",
    "Sword Art Online:Alicization",
    "Sword Oratoria:Is it Wrong to Try to Pick Up Girls in a Dungeon? On the Side",
    "Symphogear",
    "Symphogear G",
    "Symphogear GX",
    "TAMAYOMI:The Baseball Girls",
    "THE IDOLM@STER",
    "THE IDOLM@STER CINDERELLA GIRLS",
    "THE IDOLM@STER CINDERELLA GIRLS 2nd SEASON",
    "THE IDOLM@STER CINDERELLA GIRLS Theater",
    "THE IDOLM@STER SideM",
    "THE IDOLM@STER SideM Wakeatte Mini!",
    "TO BE HERO",
    "TONIKAWA:Over the Moon For You",
    "TSUKIUTA. The Animation",
    "TWOCAR",
    "Tabi Machi Late Show",
    "Taboo Tattoo",
    "Tactical Roar",
    "Tactics",
    "Tada Never Falls in Love",
    "Taisho Baseball Girls",
    "Taishou Mebiusline: Chicchai-san",
    "Taiso Samurai",
    "Takamiya Nasuno Desu!: Teekyuu Spin-off",
    "Takarajima",
    "Takunomi",
    "Tales of Eternia",
    "Tales of Saiunkoku",
    "Tales of Zestiria the Cross 2nd Season",
    "Tales of Zestiria the X",
    "Tales of the Abyss",
    "Tamako Market",
    "Tamayura: Hitotose",
    "Tamayura: More Aggressive",
    "Tanaka-kun is Always Listless",
    "Tanoshii Muumin Ikka",
    "Tantei Kageki Milky Holmes TD",
    "Tantei Opera Milky Holmes",
    "Tantei Team KZ Jiken Note",
    "Tari Tari",
    "Tayutama: Kiss on My Deity",
    "Teacher's Time",
    "Tears to Tiara",
    "Teasing Master Takagi-san",
    "Teekyu",
    "Teekyu 2",
    "Teekyu 3",
    "Teekyu 4",
    "Teekyu 5",
    "Teekyu 6",
    "Teekyu 7",
    "Teekyu 8",
    "Teekyu 9",
    "Tegami Bachi:Letter Bee",
    "Tegami Bachi:Letter Bee Reverse",
    "Tekkaman Blade",
    "Telepathy Shoujo Ran",
    "Tenchi Muyou!",
    "Tenchi Muyou! GXP",
    "Tenchi in Tokyo",
    "Tenjho Tenge",
    "Tenka Hyakken: Meiji-kan e Youkoso!",
    "Tenshi no Shippo Chu!",
    "Tentai Senshi Sunred",
    "Tentai Senshi Sunred 2nd Season",
    "Terra Formars: Revenge",
    "Terra e... (TV)",
    "Terraformars",
    "Terror in Resonance",
    "Tesagure! Bukatsumono",
    "Tesagure! Bukatsumono Encore",
    "Tesagure! Bukatsumono Spin-off Purupurun Sharumu to Asobou",
    "Texhnolyze",
    "That Time I Got Reincarnated as a Slime",
    "The \"Hentai\" Prince and the Stony Cat.",
    "The 8th son? Are you kidding me?",
    "The Ambition of Oda Nobuna",
    "The Ancient Magus' Bride",
    "The Asterisk War",
    "The Asterisk War Season 2",
    "The Betrayal Knows My Name",
    "The Big O",
    "The Case Files of Jeweler Richard",
    "The Comic Artist and His Assistants",
    "The Cosmopolitan Prayers",
    "The Daughter of 20 Faces",
    "The Day I Became a God",
    "The Demon Girl Next Door",
    "The Devil Lady",
    "The Devil is a Part-Timer!",
    "The Disappearance of Nagato Yuki-chan",
    "The Disastrous Life of Saiki K.",
    "The Disastrous Life of Saiki K. 2",
    "The Eccentric Family",
    "The Eccentric Family 2",
    "The Eden of Grisaia",
    "The Everyday Tales of a Cat God",
    "The Familiar of Zero",
    "The Familiar of Zero F",
    "The Familiar of Zero:Knight of the Twin Moons",
    "The Familiar of Zero:Rondo of Princesses",
    "The File of Young Kindaichi Returns",
    "The Fruit of Grisaia",
    "The Future Diary",
    "The Galaxy Railways",
    "The Girl Who Leapt Through Space",
    "The Girl in Twilight",
    "The Glass Mask Year 3 Class D",
    "The God of High School",
    "The Gokusen",
    "The Good Witch Of The West",
    "The Great Passage",
    "The Helpful Fox Senko-san",
    "The Heroic Legend of Arslan",
    "The Heroic Legend of Arslan:Dust Storm Dance",
    "The Highschool Life of a Fudanshi",
    "The Irregular at Magic High School",
    "The Irregular at Magic High School:Visitor Arc",
    "The Irresponsible Captain Tylor",
    "The Irresponsible Galaxy\u2606Tylor",
    "The Junji Ito Collection",
    "The Kawai Complex Guide to Manors and Hostel Behavior",
    "The Knight in the Area",
    "The Laughing Salesman",
    "The Law of Ueki",
    "The Legend of the Legendary Heroes",
    "The Lost Village",
    "The Magnificent Kotobuki",
    "The Magnificent Zorro",
    "The Master of Ragnarok & Blesser of Einherjar",
    "The Melancholy of Haruhi Suzumiya",
    "The Melancholy of Haruhi Suzumiya Season 2",
    "The Melody of Oblivion",
    "The Millionaire Detective \u2013 Balance:UNLIMITED",
    "The Misfit of Demon King Academy",
    "The Morose Mononokean",
    "The Morose Mononokean II",
    "The Mysterious Cities of Gold",
    "The Mystic Archives of Dantalian",
    "The Ones Within",
    "The Perfect Insider",
    "The Pet Girl of Sakurasou",
    "The Pilot's Love Song",
    "The Ping-Pong Club",
    "The Price of Smiles",
    "The Prince of Tennis",
    "The Prince of Tennis II",
    "The Promised Neverland",
    "The Quintessential Quintuplets",
    "The Qwaser of Stigmata",
    "The Qwaser of Stigmata II",
    "The Reflection",
    "The Rising of the Shield Hero",
    "The Rolling Girls",
    "The Rose of Versailles",
    "The Royal Tutor",
    "The Ryuo's Work is Never Done!",
    "The Sacred Blacksmith",
    "The Saga of Tanya the Evil",
    "The Seven Deadly Sins",
    "The Seven Deadly Sins:Revival of the Commandments",
    "The Seven Deadly Sins:Signs of Holy War",
    "The Seven Deadly Sins:Wrath of the Gods",
    "The Seven Heavenly Virtues",
    "The Seven Metamorphoses of Yamato Nadeshiko",
    "The Severing Crime Edge",
    "The Silver Guardian",
    "The Silver Guardian 2",
    "The Skull Man",
    "The Squid Girl",
    "The Squid Girl 2",
    "The Story of Saiunkoku",
    "The Tatami Galaxy",
    "The Testament of Sister New Devil",
    "The Testament of Sister New Devil:Burst",
    "The Third: Aoi Hitomi no Shoujo",
    "The Thousand Noble Musketeers",
    "The Troubled Life of Miss Kotoura",
    "The Twelve Kingdoms",
    "The Vision of Escaflowne",
    "The World God Only Knows",
    "The World God Only Knows II",
    "The World God Only Knows:Goddesses",
    "The World YAMIZUKAN",
    "The World is Still Beautiful",
    "The World of Narue",
    "Thermae Romae",
    "This Art Club Has a Problem!",
    "This Boy is a Professional Wizard",
    "This Ugly Yet Beautiful World",
    "Those Who Hunt Elves",
    "Those Who Hunt Elves II",
    "Three Leaves, Three Colors",
    "Tide-Line Blue",
    "Tiger & Bunny",
    "Tiger Mask W",
    "Time Bokan 24",
    "Time Travel Girl",
    "Time of Shura",
    "To Heart",
    "To Heart 2",
    "To Heart: Remember My Memories",
    "To LOVE Ru",
    "To LOVE Ru Darkness",
    "To LOVE Ru Darkness 2",
    "To the Abandoned Sacred Beasts",
    "Togainu no Chi",
    "Toilet-bound Hanako-kun",
    "Tokimeki Memorial",
    "Tokko",
    "Tokyo ESP",
    "Tokyo Ghoul",
    "Tokyo Ghoul \u221aA",
    "Tokyo Ghoul:re",
    "Tokyo Ghoul:re 2nd Season",
    "Tokyo Magnitude 8.0",
    "Tokyo Majin",
    "Tokyo Majin Gakuen Kenpucho: Tou Dai Ni Maku",
    "Tokyo Ravens",
    "Tokyo Tribe 2",
    "Tokyo Underground",
    "Tomorrow's Joe",
    "Tomorrow's Nadja",
    "Tonagura!",
    "Tonari no Seki-kun:The Master of Killing Time",
    "Tonkatsu DJ Agetarou",
    "Tono to Issho: Gantai no Yabou",
    "Tono to Issho: Ippunkan Gekijou",
    "Top Secret: The Revelation",
    "Toradora!",
    "Toriko",
    "Touch",
    "Touhai Densetsu Akagi: Yami ni Maiorita Tensai",
    "Touka Gettan",
    "Touken Ranbu - Hanamaru",
    "Tower of Druaga:The Aegis of Uruk",
    "Tower of Druaga:The Sword of Uruk",
    "Tower of God",
    "Transformers Armada",
    "Triage X",
    "Tribe Cool Crew",
    "Trickster",
    "Trigun",
    "Trinity Blood",
    "Trinity Seven",
    "True Tears",
    "Try Knights",
    "Tsubasa RESERVoir CHRoNiCLE",
    "Tsubasa RESERVoir CHRoNiCLE Season Two",
    "Tsugu Tsugumomo",
    "Tsugumomo",
    "Tsuki wa Higashi ni Hi wa Nishi ni: Operation Sanctuary",
    "Tsukigakirei",
    "Tsukimonogatari",
    "Tsukipro The Animation",
    "Tsukuyomi:Moon Phase",
    "Tsuredure Children",
    "Tsurune: Kazemai Koukou Kyuudoubu",
    "Tsuyokiss",
    "Tweeny Witches",
    "Twin Angel:Twinkle Paradise",
    "Twin Angels Break",
    "Twin Love",
    "Twin Spica",
    "Twin Star Exorcists",
    "Tytania",
    "UFO Ultramaiden Valkyrie",
    "UFO Ultramaiden Valkyrie 2:December Nocturne",
    "UQ Holder!",
    "Uchitama?! Have you seen my Tama?",
    "Ultimate Girls",
    "Ultimate Otaku Teacher",
    "Ultramaniac - Magical Girl",
    "Ulysses:Jeanne d'Arc and the Alchemist Knight",
    "Umamusume:Pretty Derby",
    "Umayon",
    "Umi Monogatari",
    "Umineko:When They Cry",
    "Un-Go",
    "Unbreakable Machine-Doll",
    "Undefeated Bahamut Chronicle",
    "Unlimited Psychic Squad",
    "Urahara",
    "Urara Meirocho",
    "Urashimasakatasen no Nichijou",
    "Urawa no Usagi-chan",
    "Urusei Yatsura",
    "Usakame",
    "Usavich",
    "Usavich II",
    "Usavich III",
    "Usavich IV",
    "Useless Witch Doremi Kaboom!",
    "Ushio & Tora",
    "Ushio and Tora",
    "Uta no Prince Sama",
    "Uta no Prince Sama 2",
    "Uta no Prince Sama Legend Star",
    "Uta no Prince Sama Revolutions",
    "Utakata",
    "Utakoi",
    "Utawarerumono",
    "Utawarerumono:The False Faces",
    "UzaMaid!",
    "Uzaki-chan Wants to Hang Out!",
    "Val x Love",
    "Valkyria Chronicles",
    "Valkyrie Drive:Mermaid",
    "Valvrave the Liberator",
    "Valvrave the Liberator 2nd Season",
    "Vampire Holmes",
    "Vampire Knight",
    "Vampire Knight:Guilty",
    "Vampire Princess Miyu",
    "Vandread",
    "Vandread: The Second Stage",
    "Vatican Miracle Examiner",
    "Venus Project:Climax",
    "Venus Versus Virus",
    "Venus to Mamoru!",
    "ViVid Strike!",
    "Vinland Saga",
    "Violet Evergarden",
    "Viper's Creed",
    "Virtual-san Looking",
    "Vividred Operation",
    "Voice of Fox",
    "Voltron:Defender of the Universe",
    "W'z",
    "WWW.WAGNARIA!!",
    "Wagamama High Spec",
    "Wagnaria!!",
    "Wagnaria!!2",
    "Wagnaria!!3",
    "Waiting in the Summer",
    "Wakaba Girl",
    "Wakakozake",
    "Wake Up, Girls!",
    "Wake Up, Girls! New Chapter",
    "Walkure Romanze",
    "Wandering Son",
    "Wandering Witch:The Journey of Elaina",
    "Wangan Midnight",
    "Wanna Be the Strongest in the World",
    "Warlords of Sigrdrifa",
    "Wasteful Days of High School Girl",
    "WataMote:No Matter How I Look At It, It's You Guys' Fault I'm Unpopular!",
    "Watashitachi, Luck Logic-bu!",
    "Wataten! An Angel Flew Down to Me",
    "Wave, Listen to Me!",
    "We Never Learn!:Bokuben",
    "We Never Learn:BOKUBEN",
    "We Rent Tsukumogami",
    "We Without Wings \u2013 Under the Innocent Sky",
    "Wedding Peach",
    "Wei\u00df Survive",
    "Wei\u00df Survive R",
    "Welcome to Demon School! Iruma-kun",
    "Welcome to Irabu's Office",
    "Welcome to the Ballroom",
    "Welcome to the N.H.K.",
    "Wellber no Monogatari: Sisters of Wellber",
    "When Supernatural Battles Became Commonplace",
    "When They Cry",
    "When They Cry:Kai",
    "Whispered Words",
    "Whistle!",
    "White Album",
    "White Album 2",
    "White Album Season 2",
    "Wild Arms",
    "Wind: A Breath of Heart (TV)",
    "Windy Tales",
    "Wise Man's Grandchild",
    "Wish Upon the Pleiades",
    "Witch Craft Works",
    "Witch Hunter Robin",
    "Witchblade",
    "Wizard Barristers",
    "Wolf Girl & Black Prince",
    "Wolf's Rain",
    "Wolverine",
    "Woodpecker Detective's Office",
    "Wooser's Hand-to-Mouth Life",
    "Wooser's Hand-to-Mouth Life:Awakening Arc",
    "Wooser's Hand-to-Mouth Life:Phantasmagoric Arc",
    "Working Buddies!",
    "Working Buddies! No 2!",
    "World Break:Aria of Curse for a Holy Swordsman",
    "World Conquest Zvezda Plot",
    "World Trigger",
    "WorldEnd:What do you do at the end of the world? Are you busy? Will you save us?",
    "Wotakoi:Love is Hard for Otaku",
    "X",
    "X-Men",
    "XL Joushi.",
    "Xenosaga The Animation",
    "Xuan Yuan Sword Luminary",
    "YU-NO:A girl who chants love at the bound of this world.",
    "Yakitate!! Japan",
    "Yamada's First Time:B Gata H Kei",
    "Yamada-kun and the Seven Witches",
    "Yamibo:Darkness, The Hat and the Travelers of the Books",
    "Yamishibai:Japanese Ghost Stories",
    "Yamishibai:Japanese Ghost Stories 2",
    "Yamishibai:Japanese Ghost Stories 3",
    "Yamishibai:Japanese Ghost Stories 4",
    "Yamishibai:Japanese Ghost Stories 5",
    "Yamishibai:Japanese Ghost Stories 6",
    "Yamishibai:Japanese Ghost Stories 7",
    "Yatogame-chan Kansatsu Nikki",
    "Yatogame-chan Kansatsu Nikki 2",
    "Yatterman Night",
    "Yawara!",
    "Yes! Precure 5 GoGo!",
    "Yes! Pretty Cure 5",
    "Yoiko",
    "Yomigaeru Sora: Rescue Wings",
    "Yona of the Dawn",
    "Yosuga no Sora",
    "Yotsuiro Biyori",
    "You Don't Know Gunma Yet",
    "You and Me 2",
    "You and Me.",
    "You're Being Summoned, Azazel",
    "You're Being Summoned, Azazel Z",
    "You're Under Arrest (1996)",
    "You're Under Arrest Mini Specials",
    "You're Under Arrest:Fast & Furious",
    "You're Under Arrest:Full Throttle",
    "Young Black Jack",
    "Your Lie in April",
    "Yowamushi Pedal",
    "Yowamushi Pedal: Glory Line",
    "Yowamushi Pedal: Grande Road",
    "Yowamushi Pedal: New Generation",
    "Yozakura Quartet",
    "Yozakura Quartet: Hana no Uta",
    "Yu Yu Hakusho:Ghost Files",
    "Yu-Gi-Oh!",
    "Yu-Gi-Oh! 5D's",
    "Yu-Gi-Oh! Arc-V",
    "Yu-Gi-Oh! GX",
    "Yu-Gi-Oh! VRAINS",
    "Yu-Gi-Oh! Zexal",
    "Yubisaki kara no Honki no Netsujou: Osananajimi wa Shouboushi",
    "Yugo The Negotiator",
    "Yuki Yuna is a Hero",
    "Yuki Yuna is a Hero:The Hero Chapter",
    "Yuki Yuna is a Hero:The Washio Sumi Chapter",
    "Yume Tsukai",
    "Yume-iro P\u00e2tissi\u00e8re",
    "Yume-iro P\u00e2tissi\u00e8re SP Professional",
    "Yumeria",
    "Yuragi-sou no Yuuna-san",
    "Yuri!!! On ICE",
    "Yurikuma Arashi",
    "Yuru Yuri San\u2606Hai!",
    "YuruYuri:Happy Go Lily",
    "YuruYuri:Happy Go Lily \u266a\u266a",
    "Yurumates 3D",
    "Yurumates 3D Plus",
    "Yusibu:I couldnt become a hero, so I reluctantly decided to get a job.",
    "Yuyushiki",
    "Yu\u2606Gi\u2606Oh!",
    "Yu\u2606Gi\u2606Oh! Zexal Second",
    "Z/X: Code Reunion",
    "Z/X: Ignition",
    "Zaion:I Wish You Were Here",
    "Zakuro",
    "Zan Sayonara Zetsubou Sensei",
    "Zatch Bell!",
    "Zegapain",
    "Zenki",
    "Zero kara Hajimeru Mahou no Sho",
    "Zetman",
    "Zettai Shounen",
    "Zipang",
    "Zoids",
    "Zoids Genesis",
    "Zoids:New Century",
    "Zoku Sayonara Zetsubou Sensei",
    "Zoku Touken Ranbu: Hanamaru",
    "Zombie Land Saga",
    "Zombie-Loan",
    "Zone of the Enders:Dolores",
    "[C] CONTROL - The Money and Soul of Possibility",
    "anohana:The Flower We Saw That Day",
    "ef - a tale of melodies.",
    "ef - a tale of memories.",
    "elDLIVE",
    "gdgd Fairies",
    "makuranodanshi",
    "number24",
    "s-CRY-ed",
    "selector infected WIXOSS",
    "selector spread WIXOSS",
    "tsuritama",
    "xxxHOLiC",
    "xxxHOLiC Kei",
    "\u2200 Gundam"
]

import json

def get_vector_json(index):
    if index >= 0 and index <= 499:
        file = open("vectors_500.json")
        return json.load(file)
    if index >= 500 and index <= 999:
        file = open("vectors_1000.json")
        return json.load(file)
    if index >= 1000 and index <= 1499:
        file = open("vectors_1500.json")
        return json.load(file)
    if index >= 1500 and index <= 1999:
        file = open("vectors_2000.json")
        return json.load(file)
    if index >= 2000 and index <= 2499:
        file = open("vectors_2500.json")
        return json.load(file)
    if index >= 2500:
        file = open("vectors_2700.json")
        return json.load(file)

def get_anime_vector(anime_name):
    if anime_name in ANIMES_LIST:
        index = ANIMES_LIST.index(anime_name)
        print(index)
        vector_json = get_vector_json(index)
        return vector_json[str(index)]